//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string StoreName { get; set; }
        public byte[] Picture { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
    }
}
